name: Production workflow

on:
  push:
    branches:
    - main

jobs:
  base-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e . --upgrade
      - name: Pack to pypi
        env:
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASS: ${{ secrets.PYPI_PASS }}
        run: |
          python -m pip install --upgrade build
          python -m pip install --user --upgrade twine
          python -m build
          python -m twine upload --username $PYPI_USER --password $PYPI_PASS --repository pypi dist/*